import Head from 'next/head';
import React, { ReactNode } from 'react';
import NavbarSignup from './signup/NavbarSignup';

const LayoutSignup = ({ children }: { children: ReactNode }) => {
  return (
    <>
      <div className="bg-black h-full ">
        <Head>
          <title>Netflix | Signup</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavbarSignup />
        <main className="h-[calc(100%-90px)] min-h-[calc(100vh-90px)] flex justify-center items-center">
          {children}
        </main>
      </div>
    </>
  );
};

export default LayoutSignup;
