import type { NextPage } from 'next';
import type { NextPageWithLayout } from './_app';
import Head from 'next/head';
import Banner from '../components/Banner';
import Row from '../components/Row';
import requests from '../services/config';
import { Movie } from '../typing';

import { useRequireAuth } from '../hooks/useAuth';
import { ReactElement } from 'react';
import { useRouter } from 'next/router';
import { useRecoilState } from 'recoil';
import { searchState } from '../atoms/atom';
import Layout from '../components/Layout';
interface Props {
  actions: Movie[];
  adventures: Movie[];
  animations: Movie[];
  dramas: Movie[];
  historys: Movie[];
  wars: Movie[];
}

const Home: NextPageWithLayout<Props> = ({
  actions,
  adventures,
  animations,
  dramas,
  historys,
  wars,
}) => {
  useRequireAuth();
  const router = useRouter();
  const [search] = useRecoilState(searchState);

  const movies = [
    { title: 'Action Movie', movies: actions },
    { title: 'Adventure Movie', movies: adventures },
    { title: 'Animation Movie', movies: animations },
    { title: 'Drama Movie', movies: dramas },
    { title: 'History Movie', movies: historys },
    { title: 'War Movie', movies: wars },
  ];

  // if (!user) {

  // }

  return (
    <div className=" relative">
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <Banner netflixOriginals={actions} />
        <section className="flex flex-col gap-5 sm:gap-8">
          {movies.map((val) => (
            <Row key={val.title} title={val.title} movies={val.movies} />
          ))}
        </section>
      </main>
    </div>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;

export const getServerSideProps = async () => {
  const [actions, adventures, animations, dramas, historys, wars] =
    await Promise.all([
      fetch(requests.fetchMovieAction).then((res) => res.json()),
      fetch(requests.fetchMovieAdventure).then((res) => res.json()),
      fetch(requests.fetchMovieAnimation).then((res) => res.json()),
      fetch(requests.fetchMovieDrama).then((res) => res.json()),
      fetch(requests.fetchMovieHistory).then((res) => res.json()),
      fetch(requests.fetchMovieWar).then((res) => res.json()),
    ]);

  return {
    props: {
      actions: actions.results,
      adventures: adventures.results,
      animations: animations.results,
      dramas: dramas.results,
      historys: historys.results,
      wars: wars.results,
    },
  };
};
